Subida de la parte 1-front
utn-integrador-III/student-service-web pull request #21
Opened 2024-07-18 05:36 UTC by edduardaq

2024-07-26 18:22 UTC, ebarahonautn requested changes
@edduardaq delete the folder **/.angular** before creating pushing your commit.

2024-07-26 18:22 UTC, ebarahonautn commented on src/app/enrollment/enrollment.service.ts
@edduardaq where do you capture any error the api can return?

2024-07-26 18:22 UTC, ebarahonautn commented on src/environments/environment.ts
this is the correct endpoint for verification code: **/user/verification**

2024-07-31 01:19 UTC, ebarahonautn requested changes
@edduardaq please review the comments added.

2024-07-31 01:19 UTC, ebarahonautn requested changes
@edduardaq solve the conflicts in the PR

2024-08-08 14:57 UTC, LilMat69 requested changes
Can you please attach the corresponding evidence to this US, in order to verify that the task has the corresponding screen with the requirements.

2024-08-09 19:27 UTC, LilMat69 approved these changes
All the images seems ok, complies with what was requested.

2024-08-09 23:59 UTC, ebarahonautn approved these changes

2024-08-09 23:59 UTC, merged