Auth Check
utn-integrador-III/student-service-web pull request #24
Opened 2024-07-25 01:07 UTC by Remma27

2024-07-25 02:23 UTC, Remma27 commented
![GetAll Zones](https://github.com/user-attachments/assets/f9426ffb-e9af-4412-944f-6ad510a3f4b3)

2024-07-26 17:55 UTC, ebarahonautn requested changes

2024-07-26 17:55 UTC, ebarahonautn commented on src/app/app.routes.ts
@Remma27
Remove the AuthGuard validation in the homepage route because user can navigate in the menu to go to lost bject screen 

`{ path: 'home', component: HomeComponent, canActivate: [AuthGuard] },`

2024-07-27 00:36 UTC, ebarahonautn approved these changes

2024-07-27 00:37 UTC, merged